### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by Mar12358** [Mar12358/book-an-appointment#13]
Team: @edahigure @Cabraham1 @everinurmind @Mar12358 
Link to [Kanban Project](https://github.com/users/Mar12358/projects/7)
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/8044a659-75da-453b-be9a-2be864fc0e78)

**Comment by Meltrust** [comment]
Hi @Mar12358,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks have been pointed, have descriptions, and assignees✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mar12358** [comment]
@Meltrust Thanks for your review!
I'm sorry about that, I copied a wrong link.
It is fixed now, you can visit the link and see the actual Kanban Board for this Project.
